spring.application.name=seif
server.servlet.context-path=/seif
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.error.whitelabel.enabled=false
#server.port=9003
springdoc.api-docs.path=/docs

spring.profiles.active=qa

auth.code.expiration=5
auth.block.expiration=10
auth.block.attemps=3
# 24 horas en milisegundos (86400000 = 24 * 60 * 60 * 1000)
token.expiration=86400000

formatos.bim.path=C:\\SEIF\\formatos_bim

management.endpoints.web.exposure.include= health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

management.metrics.export.defaults.enabled=true
management.endpoint.metrics.enabled=true
management.metrics.tags.application=seif-core

# Duración access token (5 a 15 min). Aquí 10 min:
security.oauth2.access-token.ttl-minutes=20

# Duración refresh token:
security.oauth2.refresh-token.ttl-days=30

# Logout: TTL de la lista de revocación (igual a exp del token)
security.oauth2.blacklist.prefix=bl:jwt:
security.oauth2.refresh.prefix=rt:
security.oauth2.jwk.kid=seif-kid-1
JWT_SECRET_BASE64=QE5jUmZValhuMnI1dTh4L0E/RChHK0tiUGRTZ1ZrWXA=
#reset pass
password-reset.ttl-minutes=30
frontend.base-url=http://172.30.28.63:7001
frontend.reset-path=/seif/int/cambio-contrasena
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#token-alta
crypto.token.hmacSecret=zYlNnE2t3X0M4D5wK7q8c1o2p3r4s5t6u7v8w9x0y1z2A3B4C5D6E7F8G9H0I1J2
# URL base del portal externo para solicitudes de estado de cuenta
bim.portal.ext.url=http://172.30.28.63:7001/seifclient/ext/
