# Configuracion base de datos
#spring.datasource.url=jdbc:h2:mem:seif;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.url=jdbc:h2:file:./data/seif;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
#spring.datasource.url=jdbc:h2:tcp://localhost:9092/mem:seif
#spring.datasource.url=jdbc:h2:tcp://localhost:9092/~/seif

#;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

#spring.h2.tcp.allow-others=true

#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#####################

# Configuracion base de datos
spring.datasource.url=jdbc:h2:mem:seif;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

#tcp
spring.h2.tcp.enabled=true
spring.h2.tcp.port=9092
spring.h2.tcp.settings=-tcpAllowOthers
#spring.h2.tcp.allow-others=true

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


#######################



#
#spring.ldap.embedded.ldif=classpath:users.ldif
#spring.ldap.embedded.base-dn=dc=bim,dc=com
#spring.ldap.embedded.port=389
#



spring.ldap.url=ldap://172.30.28.63:10389
#spring.ldap.url=ldap://localhost:10389
spring.ldap.base=dc=bim,dc=com
#spring.ldap.username=uid=admin,ou=system
#spring.ldap.password=secret

######Configuracion de base de datos mysql
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sief-bim-db?useSSL=false&serverTimezone=UTC
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB

#muestra una traza mas detallada
debug=true

#redis port

ftp.host=drive.bim.mx
ftp.port=22
ftp.user=VMalvaez
ftp.password=6%f1exo-k0Ef
ftp.path=/BranchBit/SEIF

#gestor.api.url=http://localhost:9002/fideicomisos
gestor.api.url=http://172.30.28.63:7001/seif-manager/fideicomisos

formatos.bim.path=C:\\SEIF\\formatos_bim
ruta.guardar.adicional=adicionales

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=5e0b618f499604
spring.mail.password=ab01accc494c28
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true