spring.ldap.url=ldap://172.30.28.63:10389
spring.ldap.base=dc=bim,dc=com


#######configuracion de base de datos sql server
spring.datasource.url=jdbc:sqlserver://;serverName=172.30.28.53\\desarrollo;databaseName=dbSEIF;port=1434;trustServerCertificate=true;Trusted_Connection=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=Erick.Castillo
spring.datasource.password=Branchbit2025
#spring.datasource.username=Guadalupe.Jarquin
#spring.datasource.password=gu4d4.z4v425

spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


#redis port

ftp.host=drive.bim.mx
ftp.port=22
ftp.user=VMalvaez
ftp.password=6%f1exo-k0Ef
ftp.path=/BranchBit/filezillaFilesServer

ruta.guardar.adicional=adicionales

gestor.api.url=http://172.30.28.63:7001/seif-manager/fideicomisos


#spring.datasource.jndi-name=jdbc/seifDS
#spring.datasource.jndi-name=java:jdbc/seifDS

# upload-multiple File
server.tomcat.max-swallow-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

formatos.bim.path=C:\\SEIF\\formatos_bim
spring.mail.host=172.30.29.38
spring.mail.port=25
#spring.mail.username=usr
#spring.mail.password=pass
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false